version: '3.7'
services:
    sparkSteps:
        build: .
        image: progetto:spark
        container_name: sparkSteps
        volumes:
            - ./apps:/apps
            - ./logs:/logs
        ports:
            - "7077:7077"
            - "9999:9999"
        environment:
            - SPARK_ACTION=spark-submit-python
            - SPARK_LOG_DIR=/logs
            - SPARK_MASTER_HOST=10.0.100.80
            - SPARK_MASTER_PORT=7077
            - SPARK_MASTER_WEBUI_PORT=9999
            - APP_NAME=w2vsteps.py
        networks: 
            progetto:
                ipv4_address: 10.0.100.80
networks:
    progetto:
        name: progetto
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24