version: '3.7'
services: 
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
        container_name: elastic-server
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_JAVA_OPTS=-Xms2g -Xmx2g
            - XPACK_SECURITY_ENABLED=false
            - xpack.security.enabled=false
            - discovery.type=single-node
        networks: 
            progetto:
                ipv4_address: 10.0.100.51
    kibana:
        build: .
        image: progetto:kibana
        container_name: kibana
        ports:
            - 5601:5601
        networks: 
            progetto:
                ipv4_address: 10.0.100.52
        depends_on:
            - elastic-search
networks:
    progetto:
        name: progetto
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24