version: '3.7'
services: 
    zookeeper:
        build: .
        image: progetto:kafka
        container_name: kafkaZK
        ports:
            - "2181:2181"
        environment:
            - KAFKA_ACTION=start-zk
        networks: 
            progetto:
                ipv4_address: 10.0.100.22
    zkui:
        image: juris/zkui
        container_name: zkui
        environment:
            - ZK_SERVER=10.0.100.22:2181
        ports:
            - 9090:9090
        networks: 
            - progetto
        depends_on:
            - zookeeper
    kafkaserver:
        build: .
        image: progetto:kafka
        container_name: kafkaServer
        environment:
            - KAFKA_ACTION=start-kafka
        ports:
            - 9092:9092
        networks: 
            progetto:
                ipv4_address: 10.0.100.23
        depends_on:
            - zookeeper
    kafkaConnect:
        build: .
        image: progetto:kafka
        container_name: kafkaConnectElastic
        environment:
            - KAFKA_ACTION=kafka-connect-elastic
        networks: 
            - progetto
        depends_on:
            - kafkatopicRecipeCleaned
            
    kafkatopicRecipe:
        build: .
        image: progetto:kafka
        depends_on:
            - kafkaserver
        environment: 
            - KAFKA_ACTION=create-topic
            - KAFKA_SERVER=10.0.100.23
            - KAFKA_TOPIC=Recipes
        networks:
            progetto:
                ipv4_address: 10.0.100.24

    kafkatopicRecipeCleaned:
        build: .
        image: progetto:kafka
        depends_on:
            - kafkatopicRecipe
        environment: 
            - KAFKA_ACTION=create-topic
            - KAFKA_SERVER=10.0.100.23
            - KAFKA_TOPIC=CleanedRecipes
        networks:
            progetto:
                ipv4_address: 10.0.100.25
      schemaRegistry:
        image: confluentinc/cp-schema-registry:latest
        depends_on:
            - kafkaServer
        environment: 
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=http://10.0.100.22:2181 
            - SCHEMA_REGISTRY_HOST_NAME=http://10.0.100.22 
            - SCHEMA_REGISTRY_LISTENERS=http://10.0.100.26:8081 
            - SCHEMA_REGISTRY_DEBUG=true
        networks:
            progetto:
                ipv4_address: 10.0.100.26


    webui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.0.100.23:9092
        ports: 
            - 8080:8080
        networks: 
            - progetto
        depends_on:
            - kafkaserver
    webui2:
        image: obsidiandynamics/kafdrop
        container_name: kafkaWebUI_2
        environment:
            - KAFKA_BROKERCONNECT=10.0.100.23:9092
        ports: 
            - 9000:9000
        networks: 
            - progetto
        depends_on:
            - kafkaserver
networks:
    progetto:
        name: progetto
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24