version: '3.7'
services: 
    zookeeper:
        build: .
        image: progetto:kafka
        container_name: kafkaZK
        ports:
            - "2181:2181"
        environment:
            - KAFKA_ACTION=start-zk
        deploy:
          resources:
            limits:
              memory: 512M
        networks: 
            progetto:
                ipv4_address: 10.0.100.22
    zkui:
        image: juris/zkui
        container_name: zkui
        environment:
            - ZK_SERVER=10.0.100.22:2181
        ports:
            - 9090:9090
        networks: 
            - progetto
        deploy:
          resources:
            limits:
              memory: 256M
        
        depends_on:
            - zookeeper
        
    kafkaserver:
        build: .
        image: progetto:kafka
        container_name: kafkaServer
        environment:
            - KAFKA_ACTION=start-kafka
        ports:
            - 9092:9092
        deploy:
          resources:
            limits:
              memory: 1024M
        
        networks: 
            progetto:
                ipv4_address: 10.0.100.23
        depends_on:
            - zookeeper

    kafkaConnect:
        build: .
        image: progetto:kafka
        container_name: kafkaConnectElastic
        environment:
            - KAFKA_ACTION=kafka-connect-elastic
        networks: 
            - progetto
        deploy:
          resources:
            limits:
              memory: 256M
        
        depends_on:
            - kafkatopicRecipeCleaned
            
    kafkatopicRecipe:
        build: .
        image: progetto:kafka
        depends_on:
            - kafkaserver
        environment: 
            - KAFKA_ACTION=create-topic
            - KAFKA_SERVER=10.0.100.23
            - KAFKA_TOPIC=Recipes
        deploy:
          resources:
            limits:
              memory: 128M
        networks:
            progetto:
                ipv4_address: 10.0.100.24

    kafkatopicRecipeCleaned:
        build: .
        image: progetto:kafka
        depends_on:
            - kafkatopicRecipe
        environment: 
            - KAFKA_ACTION=create-topic
            - KAFKA_SERVER=10.0.100.23
            - KAFKA_TOPIC=CleanedRecipes
        deploy:
          resources:
            limits:
              memory: 128M
        networks:
            progetto:
                ipv4_address: 10.0.100.25

      kafkatopicIngredients:
        build: .
        image: progetto:kafka
        depends_on:
            - kafkatopicRecipe
        environment: 
            - KAFKA_ACTION=create-topic
            - KAFKA_SERVER=10.0.100.23
            - KAFKA_TOPIC=Ingredients
        deploy:
          resources:
            limits:
              memory: 128M
        networks: 
            - progetto        
    webui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.0.100.23:9092
        ports: 
            - 8080:8080
        networks: 
            - progetto
        depends_on:
            - kafkaserver
        deploy:
          resources:
            limits:
              memory: 512M
networks:
    progetto:
        name: progetto
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24